# Generated by Django 4.0.6 on 2022-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
